// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: vote.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordVoteRequest_VoteType int32

const (
	RecordVoteRequest_UPVOTE   RecordVoteRequest_VoteType = 0
	RecordVoteRequest_DOWNVOTE RecordVoteRequest_VoteType = 1
)

// Enum value maps for RecordVoteRequest_VoteType.
var (
	RecordVoteRequest_VoteType_name = map[int32]string{
		0: "UPVOTE",
		1: "DOWNVOTE",
	}
	RecordVoteRequest_VoteType_value = map[string]int32{
		"UPVOTE":   0,
		"DOWNVOTE": 1,
	}
)

func (x RecordVoteRequest_VoteType) Enum() *RecordVoteRequest_VoteType {
	p := new(RecordVoteRequest_VoteType)
	*p = x
	return p
}

func (x RecordVoteRequest_VoteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordVoteRequest_VoteType) Descriptor() protoreflect.EnumDescriptor {
	return file_vote_proto_enumTypes[0].Descriptor()
}

func (RecordVoteRequest_VoteType) Type() protoreflect.EnumType {
	return &file_vote_proto_enumTypes[0]
}

func (x RecordVoteRequest_VoteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecordVoteRequest_VoteType.Descriptor instead.
func (RecordVoteRequest_VoteType) EnumDescriptor() ([]byte, []int) {
	return file_vote_proto_rawDescGZIP(), []int{0, 0}
}

type RecordVoteRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	SubmissionId  string                     `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	VoteType      RecordVoteRequest_VoteType `protobuf:"varint,2,opt,name=vote_type,json=voteType,proto3,enum=v1.RecordVoteRequest_VoteType" json:"vote_type,omitempty"` // Note: user_id is extracted from gRPC Metadata (JWT) by the service
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordVoteRequest) Reset() {
	*x = RecordVoteRequest{}
	mi := &file_vote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordVoteRequest) ProtoMessage() {}

func (x *RecordVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordVoteRequest.ProtoReflect.Descriptor instead.
func (*RecordVoteRequest) Descriptor() ([]byte, []int) {
	return file_vote_proto_rawDescGZIP(), []int{0}
}

func (x *RecordVoteRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *RecordVoteRequest) GetVoteType() RecordVoteRequest_VoteType {
	if x != nil {
		return x.VoteType
	}
	return RecordVoteRequest_UPVOTE
}

type RecordVoteResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ThresholdReached bool                   `protobuf:"varint,3,opt,name=threshold_reached,json=thresholdReached,proto3" json:"threshold_reached,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecordVoteResponse) Reset() {
	*x = RecordVoteResponse{}
	mi := &file_vote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordVoteResponse) ProtoMessage() {}

func (x *RecordVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordVoteResponse.ProtoReflect.Descriptor instead.
func (*RecordVoteResponse) Descriptor() ([]byte, []int) {
	return file_vote_proto_rawDescGZIP(), []int{1}
}

func (x *RecordVoteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecordVoteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RecordVoteResponse) GetThresholdReached() bool {
	if x != nil {
		return x.ThresholdReached
	}
	return false
}

var File_vote_proto protoreflect.FileDescriptor

const file_vote_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"vote.proto\x12\x02v1\"\x9b\x01\n" +
	"\x11RecordVoteRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12;\n" +
	"\tvote_type\x18\x02 \x01(\x0e2\x1e.v1.RecordVoteRequest.VoteTypeR\bvoteType\"$\n" +
	"\bVoteType\x12\n" +
	"\n" +
	"\x06UPVOTE\x10\x00\x12\f\n" +
	"\bDOWNVOTE\x10\x01\"u\n" +
	"\x12RecordVoteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x11threshold_reached\x18\x03 \x01(\bR\x10thresholdReached2J\n" +
	"\vVoteService\x12;\n" +
	"\n" +
	"RecordVote\x12\x15.v1.RecordVoteRequest\x1a\x16.v1.RecordVoteResponseB/Z-github.com/watup-lk/vote-service/api/proto/v1b\x06proto3"

var (
	file_vote_proto_rawDescOnce sync.Once
	file_vote_proto_rawDescData []byte
)

func file_vote_proto_rawDescGZIP() []byte {
	file_vote_proto_rawDescOnce.Do(func() {
		file_vote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vote_proto_rawDesc), len(file_vote_proto_rawDesc)))
	})
	return file_vote_proto_rawDescData
}

var file_vote_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vote_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vote_proto_goTypes = []any{
	(RecordVoteRequest_VoteType)(0), // 0: v1.RecordVoteRequest.VoteType
	(*RecordVoteRequest)(nil),       // 1: v1.RecordVoteRequest
	(*RecordVoteResponse)(nil),      // 2: v1.RecordVoteResponse
}
var file_vote_proto_depIdxs = []int32{
	0, // 0: v1.RecordVoteRequest.vote_type:type_name -> v1.RecordVoteRequest.VoteType
	1, // 1: v1.VoteService.RecordVote:input_type -> v1.RecordVoteRequest
	2, // 2: v1.VoteService.RecordVote:output_type -> v1.RecordVoteResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vote_proto_init() }
func file_vote_proto_init() {
	if File_vote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vote_proto_rawDesc), len(file_vote_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vote_proto_goTypes,
		DependencyIndexes: file_vote_proto_depIdxs,
		EnumInfos:         file_vote_proto_enumTypes,
		MessageInfos:      file_vote_proto_msgTypes,
	}.Build()
	File_vote_proto = out.File
	file_vote_proto_goTypes = nil
	file_vote_proto_depIdxs = nil
}
